name: Generate snake animation  # ğŸ Generates a snake animation for GitHub contributions

on:
  schedule:  # â° Executes the workflow on a scheduled basis
    - cron: "* */12 * * *"  # ğŸ• Executes every 12 hours
  workflow_dispatch:  # ğŸ”„ Allows manual triggering of the workflow
  push:  # ğŸ“¤ Triggered on a push event
    branches:
      - master  # ğŸŒ¿ The branch to trigger the action on

jobs:
  generate:
    permissions:
      contents: write  # âœï¸ Grants write permissions for the repository contents
    runs-on: ubuntu-latest  # ğŸ’» Runs the workflow on the latest Ubuntu runner
    timeout-minutes: 5  # â³ Timeout after 5 minutes if the job takes too long

    steps:
      - name: generate snake.svg  # ğŸ–¼ Generates the snake animation as an SVG file
        uses: Platane/snk/svg-only@v3  # ğŸ Uses the Platane/snk action to generate the SVG file
        with:
          github_user_name: ${{ github.repository_owner }}  # ğŸ”‘ Uses the repository owner's GitHub username
          outputs: dist/snake.svg?palette=github-dark  # ğŸ¨ Generates the SVG with a GitHub dark theme palette

      - name: push snake.svg to the output branch  # ğŸ“¤ Pushes the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # ğŸŒ Deploys the SVG to GitHub Pages
        with:
          target_branch: output  # ğŸ”„ Specifies the target branch for output
          build_dir: dist  # ğŸ“‚ Directory containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ğŸ”‘ Uses the GitHub token for authentication
